name: OpenStack Terraform Deployment

on:
  push:
    branches:
      - main
  workflow_dispatch:

jobs:
  deploy:
    runs-on: ubuntu-latest

    strategy:
      matrix:
        scenario: [
          "dfw3-rocky9-local-disk-deployment",
          "dfw3-rocky9-volume-deployment"
        ]

    env:
      OS_AUTH_URL: ${{ secrets.OS_AUTH_URL }}
      OS_PROJECT_ID: ${{ secrets.OS_PROJECT_ID }}
      OS_PROJECT_NAME: ${{ secrets.OS_PROJECT_NAME }}
      OS_PROJECT_DOMAIN_NAME: ${{ secrets.OS_PROJECT_DOMAIN_NAME }}
      OS_USER_DOMAIN_NAME: ${{ secrets.OS_USER_DOMAIN_NAME }}
      OS_USERNAME: ${{ secrets.OS_USERNAME }}
      OS_PASSWORD: ${{ secrets.OS_PASSWORD }}
      OS_REGION_NAME: ${{ secrets.OS_REGION_NAME }}
      OS_INTERFACE: ${{ secrets.OS_INTERFACE }}
      OS_IDENTITY_API_VERSION: ${{ secrets.OS_IDENTITY_API_VERSION }}
      OS_PRIVATE_KEY: ${{ secrets.OS_PRIVATE_KEY }}
      DEFAULT_SSH_USER: rocky   # <-- Update this if needed

    steps:
    - name: Checkout code
      uses: actions/checkout@v2

    - name: Set up Terraform
      uses: hashicorp/setup-terraform@v2
      with:
        terraform_version: 1.5.7

    - name: Terraform Init
      working-directory: openstack_compute_instance_v2/${{ matrix.scenario }}
      run: terraform init

    - name: Terraform Plan
      working-directory: openstack_compute_instance_v2/${{ matrix.scenario }}
      run: terraform plan -out=tfplan

    - name: Terraform Apply
      working-directory: openstack_compute_instance_v2/${{ matrix.scenario }}
      run: terraform apply tfplan

    - name: Discover Floating IPs from Terraform State
      id: get_floating_ips
      working-directory: openstack_compute_instance_v2/${{ matrix.scenario }}
      run: |
        echo "🔍 Fetching Terraform State..."
        terraform state pull > terraform_state.json
        
        echo "🔍 Validating Terraform State JSON..."
        if ! jq empty terraform_state.json > /dev/null 2>&1; then
          echo "❌ Terraform state JSON is not valid. Dumping contents:"
          cat terraform_state.json
          exit 1
        fi
        
        echo "🔍 Parsing Floating IP Associations..."
        
        # Extract both `openstack_networking_floatingip_associate_v2` and `openstack_networking_floatingip_v2`
        jq -r '
          .resources[] |
          select(
            (.type == "openstack_networking_floatingip_v2" or 
            .type == "openstack_networking_floatingip_associate_v2") 
          ) | 
          .instances[] | 
          select(.attributes.floating_ip != null) |
          "\(.index_key) \(.attributes.floating_ip)"
        ' terraform_state.json > floating_ips.txt
        
        # Validate output
        if [ ! -s floating_ips.txt ]; then
          echo "❌ No Floating IPs found."
          exit 1
        fi

        echo "✅ Floating IPs found and ready for SSH testing:"
        cat floating_ips.txt

    - name: Test SSH Connectivity
      run: |
        echo "$OS_PRIVATE_KEY" > private_key.pem
        chmod 600 private_key.pem
        
        while IFS= read -r line; do
          NAME=$(echo $line | awk '{print $1}')
          IP=$(echo $line | awk '{print $2}')
          echo "🔍 Testing SSH Connectivity to $NAME ($IP)"
          
          # Retry logic (12 attempts, 10 seconds apart)
          MAX_ATTEMPTS=12
          ATTEMPT=1
          while [ $ATTEMPT -le $MAX_ATTEMPTS ]; do
            echo "Attempt $ATTEMPT of $MAX_ATTEMPTS: Trying to connect to $IP..."
            nc -z -w5 $IP 22 && break
            ATTEMPT=$((ATTEMPT + 1))
            sleep 10
          done

          # Final SSH attempt if port 22 is reachable
          if [ $ATTEMPT -le $MAX_ATTEMPTS ]; then
            ssh -o StrictHostKeyChecking=no -i private_key.pem $DEFAULT_SSH_USER@$IP "echo 'SSH Connection Successful to $NAME'" \
              && echo "$NAME ($IP) - ✅ SSH Success" \
              || echo "$NAME ($IP) - ❌ SSH Failed"
          else
            echo "❌ Could not reach SSH on $NAME ($IP) after $MAX_ATTEMPTS attempts."
          fi
        done < floating_ips.txt
        
        # Clean up the private key after testing
        rm -f private_key.pem
    
    - name: Terraform Destroy (Cleanup)
      if: always()
      working-directory: openstack_compute_instance_v2/${{ matrix.scenario }}
      run: terraform destroy -auto-approve
