name: OpenStack Terraform Deployment

on:
  push:
    branches:
      - main
  workflow_dispatch:

jobs:
  deploy:
    runs-on: ubuntu-latest

    strategy:
      matrix:
        scenario: [
          "dfw3-rocky9-local-disk-deployment",
          "dfw3-rocky9-volume-deployment"
        ]

    env:
      OS_AUTH_URL: ${{ secrets.OS_AUTH_URL }}
      OS_PROJECT_ID: ${{ secrets.OS_PROJECT_ID }}
      OS_PROJECT_NAME: ${{ secrets.OS_PROJECT_NAME }}
      OS_PROJECT_DOMAIN_NAME: ${{ secrets.OS_PROJECT_DOMAIN_NAME }}
      OS_USER_DOMAIN_NAME: ${{ secrets.OS_USER_DOMAIN_NAME }}
      OS_USERNAME: ${{ secrets.OS_USERNAME }}
      OS_PASSWORD: ${{ secrets.OS_PASSWORD }}
      OS_REGION_NAME: ${{ secrets.OS_REGION_NAME }}
      OS_INTERFACE: ${{ secrets.OS_INTERFACE }}
      OS_IDENTITY_API_VERSION: ${{ secrets.OS_IDENTITY_API_VERSION }}
      OS_PRIVATE_KEY: ${{ secrets.OS_PRIVATE_KEY }}

    steps:
    - name: Checkout code
      uses: actions/checkout@v2

    - name: Set up Terraform
      uses: hashicorp/setup-terraform@v2
      with:
        terraform_version: 1.5.7

    - name: Terraform Init
      working-directory: openstack_compute_instance_v2/${{ matrix.scenario }}
      run: terraform init

    - name: Terraform Plan
      working-directory: openstack_compute_instance_v2/${{ matrix.scenario }}
      run: terraform plan -out=tfplan

    - name: Terraform Apply
      working-directory: openstack_compute_instance_v2/${{ matrix.scenario }}
      run: terraform apply tfplan

    - name: Extract Terraform Outputs and Debug
      id: extract_outputs
      working-directory: openstack_compute_instance_v2/${{ matrix.scenario }}
      run: |
        terraform output -json > tf_output.json
        
        # ====> Step 1: Dump Full JSON <====
        echo "🔍 Full JSON output from Terraform:"
        cat tf_output.json | tee tf_output.log

        # ====> Step 2: List All Keys <====
        echo "🔍 Top-level keys in Terraform output:"
        jq 'keys' tf_output.json | tee keys.log
        
        # ====> Step 3: Parse Each Key Separately <====
        
        # 1. Floating IPs
        if jq -e '.floating_ips.value' tf_output.json > /dev/null; then
          echo "✅ floating_ips found, extracting IPs..."
          jq '.floating_ips.value | to_entries[] | "\(.key) \(.value)"' tf_output.json > floating_ips.txt
          echo "✅ Extracted Floating IPs:"
          cat floating_ips.txt
        else
          echo "❌ 'floating_ips.value' not found or empty."
        fi
        
        # 2. Additional NICs Ports
        if jq -e '.additional_nics_ports.value' tf_output.json > /dev/null; then
          echo "✅ additional_nics_ports found."
          jq '.additional_nics_ports.value' tf_output.json > additional_nics_ports.log
        else
          echo "❌ 'additional_nics_ports.value' not found or empty."
        fi
        
        # 3. Additional Volumes
        if jq -e '.additional_volumes.value' tf_output.json > /dev/null; then
          echo "✅ additional_volumes found."
          jq '.additional_volumes.value' tf_output.json > additional_volumes.log
        else
          echo "❌ 'additional_volumes.value' not found or empty."
        fi
        
        # 4. VM IDs
        if jq -e '.vm_ids.value' tf_output.json > /dev/null; then
          echo "✅ vm_ids found."
          jq '.vm_ids.value | to_entries[] | "\(.key) \(.value)"' tf_output.json > vm_ids.txt
          echo "✅ Extracted VM IDs:"
          cat vm_ids.txt
        else
          echo "❌ 'vm_ids.value' not found or empty."
        fi

    - name: Test SSH Connectivity with Retry
      working-directory: openstack_compute_instance_v2/${{ matrix.scenario }}
      run: |
        echo "$OS_PRIVATE_KEY" > private_key.pem
        chmod 600 private_key.pem
        
        while IFS= read -r line; do
          NAME=$(echo $line | awk '{print $1}')
          IP=$(echo $line | awk '{print $2}')
          echo "Testing SSH Connectivity to $NAME ($IP)"
          
          # Retry logic (12 attempts, 10 seconds apart)
          MAX_ATTEMPTS=12
          ATTEMPT=1
          while [ $ATTEMPT -le $MAX_ATTEMPTS ]; do
            echo "Attempt $ATTEMPT of $MAX_ATTEMPTS: Trying to connect to $IP..."
            nc -z -w5 $IP 22 && break
            ATTEMPT=$((ATTEMPT + 1))
            sleep 10
          done

          # Final SSH attempt if port 22 is reachable
          if [ $ATTEMPT -le $MAX_ATTEMPTS ]; then
            ssh -o StrictHostKeyChecking=no -i private_key.pem ubuntu@$IP "echo 'SSH Connection Successful to $NAME'" \
              && echo "$NAME ($IP) - ✅ SSH Success" \
              || echo "$NAME ($IP) - ❌ SSH Failed"
          else
            echo "❌ Could not reach SSH on $NAME ($IP) after $MAX_ATTEMPTS attempts."
          fi
        done < floating_ips.txt

    - name: Terraform Destroy (Cleanup)
      if: always()
      working-directory: openstack_compute_instance_v2/${{ matrix.scenario }}
      run: terraform destroy -auto-approve
